### ISSUE TITLE
Add findbugs to project

### ISSUE THREAD

**Issue by gergelydaniel** [gergelydaniel/outlay#1]
Add [findbugs](http://findbugs.sourceforge.net/) to project

**Comment by pr1stvan** [comment]
Review OK

**Comment by micskeiz** [comment]
Have you run FindBugs? Did it find any bugs? Have you looked into the results?

**Comment by pr1stvan** [comment]
Yes, we've run it, and in our opinion it doesn't contain any critical warnings.
results: https://github.com/gergelydaniel/outlay/wiki/Findbugs-report
